# Diccionario de palabras conocidas
diccionario_palabras = {
    "casa": None,
    "hola": None,
    "adiós": None,
    "buenos": None,
    "días": None,
    "noches": None,
    "por": None,
    "favor": None,
    "gracias": None,
    "de": None,
    "nada": None,
    "sí": None,
    "no": None,
    "quizás": None,
    "tal": None,
    "vez": None,
    "ahora": None,
    "luego": None,
    "más": None,
    "tarde": None,
    "temprano": None,
    "después": None,
    "antes": None,
    "aquí": None,
    "allí": None,
    "cerca": None,
    "lejos": None,
    "arriba": None,
    "abajo": None,
    "dentro": None,
    "fuera": None,
    "izquierda": None,
    "derecha": None,
    "encima": None,
    "debajo": None,
    "entre": None,
    "alrededor": None,
    "delante": None,
    "detrás": None,
    "sigue": None,
    "espera": None,
    "detente": None,
    "avanza": None,
    "retrocede": None,
    "gira": None,
    "bordo": None,
    "estribor": None,
    "babor": None,
    "tierra": None,
    "mar": None,
    "aire": None,
    "fuego": None,
    "agua": None,
    "viento": None,
    "sol": None,
    "luna": None,
    "estrellas": None,
    "cielo": None,
    "nube": None,
    "lluvia": None,
    "nieve": None,
    "frío": None,
    "calor": None,
    "verano": None,
    "invierno": None,
    "primavera": None,
    "otoño": None,
    "hombre": None,
    "mujer": None,
    "niño": None,
    "niña": None,
    "persona": None,
    "gente": None,
    "amigo": None,
    "amiga": None,
    "familia": None,
    "padre": None,
    "madre": None,
    "hermano": None,
    "hermana": None,
    "hijo": None,
    "hija": None,
    "abuelo": None,
    "abuela": None,
    "tío": None,
    "tía": None,
    "sobrino": None,
    "sobrina": None,
    "primo": None,
    "prima": None,
    "esposo": None,
    "esposa": None,
    "novio": None,
    "novia": None,
    "vecino": None,
    "vecina": None,
    "colega": None,
    "compañero": None,
    "compañera": None,
    "jefe": None,
    "jefa": None,
    "cliente": None,
    "profesor": None,
    "profesora": None,
    "alumno": None,
    "alumna": None,
    "médico": None,
    "doctor": None,
    "doctora": None,
    "enfermero": None,
    "enfermera": None,
    "policía": None,
    "oficial": None,
    "soldado": None,
    "bombero": None,
    "ingeniero": None,
    "abogado": None,
    "abogada": None,
    "arquitecto": None,
    "diseñador": None,
    "cocinero": None,
    "cocinera": None,
    "mesero": None,
    "mesera": None,
    "taxista": None,
    "conductor": None,
    "pasajero": None,
    "pasajera": None,
    "viajero": None,
    "viajera": None,
    "turista": None,
    "guía": None,
    "visitante": None,
    "huésped": None,
    "anfitrión": None,
    "anfitriona": None,
    "comprador": None,
    "vendedor": None,
    "trabajador": None,
    "trabajadora": None,
    "empleado": None,
    "empleada": None,
    "jubilado": None,
    "jubilada": None,
    "estudiante": None,
    "público": None,
    "privado": None,
    "gratis": None,
    "pagado": None,
    "dinero": None,
    "efectivo": None,
    "tarjeta": None,
    "crédito": None,
    "débito": None,
    "cuenta": None,
    "banco": None,
    "cajero": None,
    "cheque": None,
    "firma": None,
    "identificación": None,
    "pasaporte": None,
    "documento": None,
    "papel": None,
    "lápiz": None,
    "pluma": None,
    "bolígrafo": None,
    "tinta": None,
    "carta": None,
    "nota": None,
    "archivo": None,
    "carpeta": None,
    "informe": None,
    "contrato": None,
    "acuerdo": None,
    "permiso": None,
    "licencia": None,
    "registro": None,
    "certificado": None,
    "titulo": None,
    "diploma": None,
    "examen": None,
    "prueba": None,
    "entrevista": None,
    "reunión": None,
    "conferencia": None,
    "evento": None,
    "fiesta": None,
    "celebración": None,
    "cumpleaños": None,
    "aniversario": None,
    "boda": None,
    "funeral": None,
    "graduación": None,
    "promoción": None,
    "viaje": None,
    "vacaciones": None,
    "excursión": None,
    "paseo": None,
    "vuelo": None,
    "avión": None,
    "barco": None,
    "tren": None,
    "coche": None,
    "autobús": None,
    "taxi": None,
    "bicicleta": None,
    "motocicleta": None,
    "rueda": None
}

#Creamos el diccionario de posibles palabras y sus siguientes letras
posibles_palabras = {}
for palabra in diccionario_palabras:
    if len(palabra) > 1:
        prefijo = palabra[:-1]  # Obtenemos el prefijo de la palabra
        ultima_letra = palabra[-1]  # Obtenemos la última letra de la palabra
        if prefijo not in posibles_palabras:
            posibles_palabras[prefijo] = []
        posibles_palabras[prefijo].append(ultima_letra)


def predecir_palabra(palabras):
    posibles_palabras = []

    # Iterar sobre todas las palabras en el diccionario
    for palabra in diccionario_palabras:
        if palabra.startswith(palabras):
            posibles_palabras.append(palabra)

    return posibles_palabras


def verificar_palabra(palabra_actual, letra_siguiente):
    if palabra_actual in posibles_palabras:
        return letra_siguiente in posibles_palabras[palabra_actual]
    else:
        return False


